### ISSUE TITLE
Handlebars missing?

### ISSUE THREAD

**Issue by JuanCaicedo** [losttype/metalsmith-register-helpers#4]
Should Handlebars be included in the dev dependencies? It's used in [index.js](https://github.com/losttype/metalsmith-register-helpers/blob/master/index.js#L3), but it's not included in `node_modules`. 

Is the goal to have this module use the `Handlebars` in the main project? That is in `../../node_modules/handlebars/`? If so, maybe a better API would be to have the user pass in a `Handlebars` instance, to insure it's always the same one. 

I could make a PR if that seems like a good approach. Let me know if you would like to know what errors I'm seeing from this too! 😃

**Comment by kennethormandy** [comment]
Sorry for the slow reply. My understanding is that Handlebars would be considered a peer dependency of the plugin, like Metalsmith, but those have gone away as part of npm@3. I basically copied this part directly from Lin Clark’s register partials plugin. I don’t think installing this plugin should necessarily install Handlebars, because that caused https://github.com/losttype/metalsmith-register-helpers/issues/1. Accepting `*` version of Handlebars as a dependency might be fine, but I’m going to leave it as-is for now. If you want to open a PR that solves it more effectively, totally open to that. Thanks!
